### ISSUE TITLE
db query error: pq: syntax error at or near ")"

### ISSUE THREAD

**Issue by karthilinux91** [cloudquery/dashboards#6]
### Describe the bug

db query error: pq: syntax error at or near ")"

### Expected Behavior

db query error: pq: syntax error at or near ")"

### Steps to Reproduce

db query error: pq: syntax error at or near ")"

### Possible Solution

db query error: pq: syntax error at or near ")"

### Provider and CloudQuery version

db query error: pq: syntax error at or near ")"

### Additional Context

db query error: pq: syntax error at or near ")"

**Comment by hermanschaaf** [comment]
Thank you for the bug report! 

I believe this error will happen if you haven't run the SQL to generate the corresponding View yet, as highlighted in the Readme:

> :warning: Note: aws_asset_inventory.json will require execution of the following [view](https://github.com/cloudquery/cq-provider-aws/blob/main/views/resources.sql) before importing the dashboard.

It was easy to miss these instructions before, so we are calling this out more in the Readme now (as of [this PR](https://github.com/cloudquery/dashboards/pull/18)). 

I will try and think of a way we can better handle this in the dashboard itself too, so that the error message can better guide you to the correct resolution.
